### ISSUE TITLE
Adding Binary Search

### ISSUE THREAD

**Issue by GSNCodes** [akshitagit/Python#25]
I would like to take and work on this issue. Please assign it to me. I'll raise a pull request for it after that.

**Comment by hritik5102** [comment]
Hello @GSNCodes , I would like to work on this issue ...

should I make a Pull request ?

Thank you

**Comment by GSNCodes** [comment]
Hi @hritik5102 
I was working on this issue and the PR was merged. Do look for other open issues.  👍 
This will be closed.
