### ISSUE TITLE
CHOOSE NUMBERS!

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/Python#3]
You are given an array of integers A.
You need to tell whether you can choose three numbers such that a+b>=c.

Input Format
First line consists of number of integers N. next line consists of N space separated integers.

Constraints
1 <= N <= 10^5

Output Format
YES or NO

Sample Input
5
1 2 3 4 9
Sample Output
YES
Explanation
you can choose 1+3 >= 4

Solve the question and raise the Pull Requests.

**Comment by sejalshri** [comment]
hey. i would like to work on this issue as a part of Hacktoberfest .please assign it to me.

**Comment by akshitagupta15june** [comment]
fork this repo , add your code and then raise a pull request

**Comment by sejalshri** [comment]
sure, i will make the PR on 1st oct.

**Comment by HimadriPathak** [comment]
can i do this plz

**Comment by sejalshri** [comment]
@akshitagupta15june ,my code is ready for this issue.Should i send the PR ? i have checked, it's code is not there yet in the repository.

**Comment by akshitagupta15june** [comment]
Ok @sejalshri
