### ISSUE TITLE
Create a basic calculator

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/Python#35]
add the code in daily code with all operations.

**Comment by Malvika18** [comment]
Hi @akshitagupta15june i would like to contribute to this issue can you please guide me.

**Comment by akshitagupta15june** [comment]
fork this repo, add your code in daily code repo and create a pull request

**Comment by jwalaprasad** [comment]
Hi @akshitagupta15june i would like to contribute to this issue.

**Comment by ion05** [comment]
Hi @akshitagupta15june i would also like to contribute to this issue.

**Comment by akshitagupta15june** [comment]
PROCESS OF CONTRIBUTION IN THIS REPOSITORY

FORK THIS REPOSITORY
ADD YOUR CODE IN RESPECTIVE FOLDER
CREATE A PULL REQUEST
AFTER A SIMPLE CHECK I WILL MERGE THE PR

HAPPY CODING AND CONTRIBUTING!!!!

**Comment by ion05** [comment]
A calculator with basic 4 operations would be valid right ?

**Comment by akshitagupta15june** [comment]
yes ofcourse , its a beginner issue

PROCESS OF CONTRIBUTION IN THIS REPOSITORY

FORK THIS REPOSITORY
ADD YOUR CODE IN RESPECTIVE FOLDER
CREATE A PULL REQUEST
AFTER A SIMPLE CHECK I WILL MERGE THE PR

HAPPY CODING AND CONTRIBUTING!!!!

**Comment by HimadriPathak** [comment]
can i do this plz

**Comment by cl0ne** [comment]
https://hacktoberfest.digitalocean.com/details#spam
