### ISSUE TITLE
code to commit

### ISSUE THREAD

**Issue by adityagupta26** [akshitagit/Python#53]
i will leave a code

**Comment by akshitagupta15june** [comment]
please specify

**Comment by adityagupta26** [comment]
// CPP program to implement run length encoding
#include <bits/stdc++.h>
using namespace std;

void printRLE(string str)
{
	int n = str.length();
	for (int i = 0; i < n; i++) {

		// Count occurrences of current character
		int count = 1;
		while (i < n - 1 && str[i] == str[i + 1]) {
			count++;
			i++;
		}

		// Print character and its count
		cout << str[i] << count;
	}
}

int main()
{
	string str = "wwwwaaadexxxxxxywww";
	printRLE(str);
	return 0;
}

**Comment by adityagupta26** [comment]
i am not able to commit request/pull request

**Comment by akshitagupta15june** [comment]
ok i will add it.
no worries
