### ISSUE TITLE
Create Binary Search

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/Python#55]

**Comment by Pulkitmahajan01** [comment]
hi @akshitagupta15june ,could you please assign me this issue.

**Comment by GSNCodes** [comment]
@akshitagupta15june  PR #27 covers this right?

**Comment by akshitagupta15june** [comment]
Asssigned

PROCESS OF CONTRIBUTION IN THIS REPOSITORY

FORK THIS REPOSITORY
ADD YOUR CODE IN RESPECTIVE FOLDER
CREATE A PULL REQUEST
AFTER A SIMPLE CHECK I WILL MERGE THE PR

HAPPY CODING AND CONTRIBUTING!!!!

**Comment by GSNCodes** [comment]
This issue should be closed right?
Refer PR #27

**Comment by akshitagupta15june** [comment]
Closed

**Comment by shaonakundu** [comment]
Hi @akshitagupta15june can you assign me this issue?
