### ISSUE TITLE
Check whether a number is prime or not?

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/Python#6]
Add code in DailyCode repo of Python.

**Comment by ion05** [comment]
Can i work on this ?

**Comment by HarshKhilawala** [comment]
I would like to take this in Java if possible @akshitagupta15june

**Comment by Gauravsaha-97** [comment]
I would like on work on this issue.

**Comment by parthsrivastava100** [comment]
I would also like to work on this issue. Can i please work on it ?

**Comment by akshitagupta15june** [comment]
issue closed.
