### ISSUE TITLE
Find HCF

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/Python#60]
Given N positive numbers, your task is to calculate their HCF.
Input Format

First line of input contains a single integer N, second line contains N space separated positive integers whose HCF is to be computed.
Constraints

N <= 10 and all the numbers lie between 1 and 100.
Output Format

Print HCF of N numbers.
Sample Input

3
2 4 6

Sample Output

2

**Comment by akshitagupta15june** [comment]
ADD IN MATHS FOLDER

**Comment by CodesOfAnurag** [comment]
hi @akshitagupta15june , can you assign me this issue?

**Comment by kchatr** [comment]
I literally created this function and the maths folder, so you should have the decency to let me fix the issue @akshitagupta15june

**Comment by shiv-ani-singh** [comment]
Can you assign this to me?
