### ISSUE TITLE
DECIMAL TO OCTAL

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/Python#62]
Take N (number in decimal format). Write a function that converts it to octal format. Print the value returned.
Input Format

Constraints

0 < N <= 1000000000
Output Format

Sample Input

63

Sample Output

77

**Comment by akshitagupta15june** [comment]
ADD IN MATHS FOLDER

**Comment by gokulrajanpillai** [comment]
I would love to take this over. Can you add me as contributor?

**Comment by keshav304** [comment]
Hey @akshitagupta15june I would love to be assigned this issue.

**Comment by Akshi149** [comment]
I would like to work on this issue

**Comment by akshitagupta15june** [comment]
ok assigning it to u

**Comment by yuvraajnarula** [comment]
I would like to work on this issue. Can you assign me this?

**Comment by maxily1** [comment]
Hey, I'd like to work on this issue. 
I will try to make something more understandable and commented than yuvraajnarula.
