### ISSUE TITLE
TRIANGLE PATTERN

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/Python#74]
Take N (number of rows), print the following pattern (for N = 4).

                       1 
                     2 3 2
                   3 4 5 4 3
                 4 5 6 7 6 5 4

Input Format

Constraints

0 < N < 10

**Comment by akshitagupta15june** [comment]
ADD IN PATTERNS FOLDER

**Comment by j-tesla** [comment]
@akshitagupta15june Please assign me.

**Comment by hritik5102** [comment]
@akshitagupta15june I would like to work on this issue .

**Comment by akshitagupta15june** [comment]
assigned to u

**Comment by hritik5102** [comment]
@akshitagupta15june Check out the PR #84 

Thank you :)
