### ISSUE TITLE
Reverse a String and print.

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/Python#95]
Star this repo
Add in string folder.
Beginner friendly issue.

**Comment by adenashameem** [comment]
Can you assign this to me?

**Comment by iriyagupta** [comment]
@akshitagupta15june Hi ! I have created a pull request for this.

**Comment by ankitgoel25** [comment]
@akshitagupta15june Please assign this issue to me! I will be solving this issue as a part of Hacktober Fest 2020.

**Comment by ion05** [comment]
@akshitagupta15june I would like to work on this issue as well

**Comment by praveen-01** [comment]
@akshitagupta15june can you assign this to me ?
